apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_SERVICE_NAME
          value: {{ template "fullname" . }}
        - name: RABBITMQ_NODE_TYPE
          value: {{ .Values.configEnvs.RABBITMQ_NODE_TYPE | quote }}
        - name: RABBITMQ_NODENAME
          value: {{ printf "%s@%s" .Values.configEnvs.RABBITMQ_NODENAME "localhost" | quote }}
        - name: RABBITMQ_CLUSTER_NODE_NAME
          value: {{ .Values.configEnvs.RABBITMQ_CLUSTER_NODE_NAME | quote }}
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.configEnvs.RABBITMQ_VHOST | quote }}
        ports:
        - name: epmd
          containerPort: 4369
        - name: ampq
          containerPort: {{ .Values.service.internalPort }}
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672
#        livenessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#        readinessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
